var months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
var days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
document.getElementById('currentDay').textContent = days[new Date().getDay()] + ", " + new Date().getDate() + " " + months[new Date().getMonth()] + ", " + new Date().getFullYear();
var timeBlocks = document.getElementById('time-block');
timeBlocks.appendChild(document.createElement('p'));
timeBlocks.appendChild(document.createElement('textarea'));
timeBlocks.appendChild(document.createElement("button"));
timeBlocks.children[0].classList.add('hour', 'col-1');
timeBlocks.children[1].classList.add('row', 'col-10');
timeBlocks.children[2].classList.add('saveBtn', 'col-1');